### ISSUE TITLE
US01 - Criar anotações

### ISSUE THREAD

**Issue by marcosadrianonery** [req-2020-2-empty-coffee-cups/backlogs-kanbans#2]
## Descrição

Eu como usuário desejo criar anotações para lembrar de conteúdos que me interessem.

**Dificuldade: 1**

## Tarefas
- [x] inicializar novo projeto Flutter no Android Studio
- [x] criar repositório principal da aplicação
- [x] atualizar os pacotes de acordo com o documento de visão
- [x] subir projeto para repositório
- [x] Visualizar uma página para criação da anotação
- [x] Salvar anotação 

## Critérios de aceitação

- [x] Não salvar anotação com corpo e titulo nulo
- [x] Salvar apenas se o botão de salvar for acionado

**Comment by DaviAntonio** [comment]
**Revisão devido a mudança de paradigmas de ágil para tradicional**
Removidos limites de tamanho dos campos de título (100) e conteúdo da anotação (500)
