### ISSUE TITLE
FT02 - Serviço de backup local

### ISSUE THREAD

**Issue by marcosadrianonery** [req-2020-2-empty-coffee-cups/backlogs-kanbans#24]
## Descrição

Descreva o que fazer nesta tarefa.

## Tarefas

- [ ] Tarefa 1
- [ ] Tarefa 2
- [ ] Tarefa 3

## Critério de aceitação

- [ ] Critério 1
- [ ] Critério 2
- [ ] Critério 3

**Comment by DaviAntonio** [comment]
Mesclada com a funcionalidade FT03 (#25)
