### ISSUE TITLE
US02 - Salvar anotações

### ISSUE THREAD

**Issue by marcosadrianonery** [req-2020-2-empty-coffee-cups/backlogs-kanbans#3]
## Descrição

Eu como usuário desejo salvar anotações para poder consultar seus conteúdos posteriormente.
**Dificuldade: 3**
## Tarefas

- [ ] Tarefa 1
- [ ] Tarefa 2
- [ ] Tarefa 3

## Critérios de aceitação

- [ ] Critério 1
- [ ] Critério 2
- [ ] Critério 3

**Comment by Jonathan-Oliveira** [comment]
Issue US02 fechada no dia 25/03/2021 por ser redundante com a US01
