### ISSUE TITLE
US03 - Visualizar anotações

### ISSUE THREAD

**Issue by marcosadrianonery** [req-2020-2-empty-coffee-cups/backlogs-kanbans#4]
## Descrição

Eu como usuário desejo visualizar anotações para visualizar as que já foram criadas.
**Dificuldade:  1**

## Tarefas

- [x] Listar as anotações existentes

## Critérios de aceitação

- [x] Mostrar apenas o titulo caso o corpo seja nulo
- [x] Passar por todas as notas por uma lista com barra de rolagem vertical

**Comment by DaviAntonio** [comment]
**Revisão devido a mudança de paradigmas de ágil para tradicional**
Serão implementados somente o descrito no novo MVP devido ao encurtamento da etapa ágil, que foi planejada para durar até o fim do projeto.
- Retirou-se a funcionalidade de arquivamento (já coberta por #16 )
- Foram retirados os limites para os campos de título e conteúdo das anotações
