### ISSUE TITLE
US04 - Editar anotações

### ISSUE THREAD

**Issue by marcosadrianonery** [req-2020-2-empty-coffee-cups/backlogs-kanbans#5]
## Descrição

Eu como usuário desejo editar anotações para que possa alterar seus conteúdos sem que seja necessário reescrevê-los completamente.
**Dificuldade: 02**

## Tarefas

- [x] Disponibilizar uma página para edição dos campos
- [x] Recuperar dados da anotação

## Critério de aceitação

- [x] Não criar uma id nova para a anotação
- [x] Recuperar titulo mesmo que seja nulo
- [x] Recuperar conteúdo mesmo que seja nulo 
- [x] Não salvar anotação com corpo e titulo nulo
- [x] Salvar apenas se o botão de salvar for acionado

**Comment by DaviAntonio** [comment]
**Revisão devido a mudança de paradigmas de ágil para tradicional**
Serão implementados somente o descrito no novo MVP devido ao encurtamento da etapa ágil, que foi planejada para durar até o fim do projeto.
- Foram retirados os limites para os campos de título (100) e conteúdo (500) das anotações
- Mover itens relativos ao suporte das etiquetas para #7 
  - Recuperar etiquetas não nulas
  - Caso a etiqueta não exista, retirar id do vetor de id de etiquetas, para o usuário não salvar a anotação com etiqueta inválida
