### ISSUE TITLE
US05 - Deletar anotações

### ISSUE THREAD

**Issue by marcosadrianonery** [req-2020-2-empty-coffee-cups/backlogs-kanbans#6]
## Descrição

Eu como usuário desejo deletar anotações para remover conteúdos que não são mais necessários.
**Dificuldade: 02**

## Tarefas

- [x] Deletar anotação no banco de dados
- [x] Mostrar mensagem de erro, caso tiver 

## Critérios de aceitação
- [x] Verificar se a anotação excluída não aparece no tela de visualização

**Comment by DaviAntonio** [comment]
**Revisão devido a mudança de paradigmas de ágil para tradicional**
Serão implementados somente o descrito no novo MVP devido ao encurtamento da etapa ágil, que foi planejada para durar até o fim do projeto.
- Retirados requisitos de validação de ato de apagar anotações
  - Mostrar mensagem para o usuário pedindo para confirmar o desejo de deletar a anotação
  - Mostrar para o usuário uma mensagem que a anotação foi deletada
  - Deletar apenas se o botão de confirmação do usuário *(critério)*
